### ISSUE TITLE
Outdated bitvec dependency

### ISSUE THREAD

**Issue by r3dlight** [rust-disk-partition-management/mbrman#24]
Hi,

funty 1.2.0 has been yanked.
bitvec = "0.22" won't build.

Is it possible to update bitvec to the latest version ?

Thanks !

**Comment by cecton** [comment]
hmm strange... this should have make the CI fail

**Comment by cecton** [comment]
Ah now it fails! ^_^ I guess things broke in the last 8 days or so... https://github.com/rust-disk-partition-management/mbrman/actions/runs/3421523692/jobs/5819310185

**Comment by r3dlight** [comment]
Great thanks, waiting for your PR to be merged :)
